In [1]:
import torch

In [12]:
a = [1.0, 2.0, 1.0]
print(a[0])
a

1.0


[1.0, 2.0, 1.0]

In [17]:
# creates a (one-dimensional) tensor of size 3 filled with the value 1.0
b = torch.ones(3)
print(b)
float(b[1])
b[2] = 2.0
b

tensor([1., 1., 1.])


tensor([1., 1., 2.])

In [32]:
d_flag = False
if d_flag:
    # Empty construction of a 3x2 Tensor
    points = torch.zeros(3, 2)
else:
    # Parameter construction of a 3x2 Tensor
    points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
# Different view of the data stored in RAM
print(points[0, 1])
points.shape

tensor(4.)


torch.Size([3, 2])

In [35]:
# the storage under the hood is a contiguous array of size 6
points_storage = points.storage()
# You can’t index a storage of a 2D tensor by using two indices
print(points_storage[0])
points_storage[1] = 2.0
print(points) # used to be 4.

1.0
tensor([[1., 2.],
        [2., 1.],
        [3., 5.]])


In [39]:
second_point = points[1]
# a tuple indicating how many elements across each dimension the tensor represents
print(second_point.size())
# the index in the storage that corresponds to the first element in the tensor
print(second_point.storage_offset())
# the number of elements in the storage that need to be skipped to obtain the next element along each dimension
print(points.stride())
# the number of rows and columns
print(second_point.shape)

torch.Size([2])
2
(2, 1)
torch.Size([2])


# Multidimensional Array Accessing
To access an element i, j in a 2D tensor results in accessing the storage_offset + stride\[0\] \* i + stride\[1\] \* j element in the storage

In [42]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
print(second_point.size())
print(second_point.storage_offset())
print(second_point.stride())

torch.Size([2])
2
(1,)


# Cloning a subtensor

In [46]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]]) 
second_point = points[1].clone()
second_point[0] = 10.0
print(points[1])
print(second_point)

tensor([2., 1.])
tensor([10.,  1.])


# Transposing a tensor
works on any tensor of any dimension

# Transposing Tensors

In [59]:
# 3x2 Tensor
# 2x3 Tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
# transposing is obtained only by creating a new Tensor instance with different stride ordering from the original
points_t = points.t()
print(points.shape)
print(points_t)
# verify that two tensors share storage
print(id(points.storage()) == id(points_t.storage()))
# they only differ in shape and stride
print(points.stride())
print(points_t.stride())

torch.Size([3, 2])
tensor([[1., 2., 3.],
        [4., 1., 5.]])
True
(2, 1)
(1, 2)


In [62]:
# You can create tensors of a specific data type
float_points = torch.ones(10, 2, dtype=torch.float)
print(float_points.dtype)

double_points = torch.ones(10, 2, dtype=torch.double)
print(double_points.dtype)

half_points = torch.ones(10, 2, dtype=torch.half)
print(half_points.dtype)

int8_points = torch.ones(10, 2, dtype=torch.int8)
print(int8_points.dtype)

uint8_points = torch.ones(10, 2, dtype=torch.uint8)
print(uint8_points.dtype)

short_points = torch.ones(10, 2, dtype=torch.short)
print(short_points.dtype)

int_points = torch.ones(10, 2, dtype=torch.int)
print(int_points.dtype)

long_points = torch.ones(10, 2, dtype=torch.long)
print(long_points.dtype)

torch.float32
torch.float64
torch.float16
torch.int8
torch.uint8
torch.int16
torch.int32
torch.int64


In [63]:
# you can cast the output of a tensor-creation function to the right type by using the corresponding casting method 
double_points1 = torch.zeros(10, 2).double() 
double_points2 = torch.zeros(10, 2).to(torch.double) 

short_points1 = torch.ones(10, 2).short()
short_points2 = torch.ones(10, 2).to(dtype=torch.short)

# Indexing tensors

In [84]:
# Range indexing notation can be used on Tensors
some_list = list(range(6)) 
# All elements in the list
some_list[:] 
# From element 1 inclusive to element 4 exclusive
some_list[1:4] 
# From element 1 inclusive to the end of the list
some_list[1:] 
# From the start of the list to element 4 exclusive
some_list[:4] 
# From the start of the list to one before the last element
some_list[:-1] 
# From element 1 inclusive to element 4 exclusive in steps of 2
some_list[1:4:2]

# Range indexing for each dimension works as well
# All rows after first, implicitly all columns
points[1:] 
# All rows after first, all column
points[1:, :] 
# All rows after first, first column
points[1:, 1:2]

# PyTorch also has advanced indexing
points[:, (0, -1)]

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

# NumPy interoperability
zero-copy interoperability with NumPy arrays is due to the storage system that works with the Python buffer protocol

In [98]:
points = torch.ones(3, 4)
points_np = points.numpy()
print(points_np)
points = torch.from_numpy(points_np)
print(points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# Serializing tensors
save Tensor data to a file and load it back at some point

In [109]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [110]:
# Tensor's Propietary file system save and load:
file_name = 'data/points.t'
# save to file
# torch.save(points, file_name)
with open(file_name,'wb') as f:
    torch.save(points, f)

points = torch.ones(3, 4)
print(points)

# load from file
#points = torch.load(file_name)
with open(file_name,'rb') as f:
    points = torch.load(f)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [135]:
# HDF5 format - accepts and returns data under the form of NumPy arrays
import h5py
file_name = 'data/points.hdf5'

# write the data to a file on disk
f = h5py.File(file_name, 'w')
# 'coords' is a key into the HDF5 file
dset = f.create_dataset('coords', data=points.numpy()) 
f.close()
# read the data from file in memory
f = h5py.File(file_name, 'r')
# access the key:value pairs representing the data, stored in memory
dset = f['coords']
# you can index the data set while on disk and access only the elements you’re interested in
last_points = dset[1:]
# then convert to a PyTorch Tensor
last_points = torch.from_numpy(dset[1:]) 
f.close()

# Moving tensors to the GPU

In [139]:
# MacOS does not have a GPU with CUDA cores
points_gpu1 = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')
points_gpu2 = points.to(device='cuda') # equivalent to points.cuda()
# You can specify which GPU ot use
points_gpu3 = points.to(device='cuda:0') # equivalent to points.cuda(0)
# Perform your GPU calculations
points_gpu1 = points_gpu1 + 4
# then convert back to cpu tensor
points_cpu = points_gpu1.to(device='cpu') # equivalent to points_gpu1.cpu()

# The tensor API

In [140]:
# transpose a tensor
a = torch.ones(3, 2) 
a_t = a.transpose(0, 1)

# empty a tensor
a = torch.ones(3, 2)
a.zero_()



tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [148]:
b = a.view(3, 3)
b[1,1]

AttributeError: 'list' object has no attribute 'view'

# Numeric types