In [1]:
import numpy as np

In [18]:
# Scalar types are a single valuee with zero dimensions
s = np.array(5)
# "()" indicates that it has zero dimensions
print("S's type = {}".format(s.shape))
# Even though scalars are inside arrays, you still use them like a normal scalar
x = s + 3
print("s + 3 = {}".format(x))
print("X's Type = {}".format(x.dtype))
print("X's Shape = {}".format(x.shape))

S's type = ()
s + 3 = 8
X's Type = int64
X's Shape = ()


In [25]:
# Vectors contain multiple scalars in either row or column format
v = np.array([1,2,3])
print("V's Type = {}".format(v.dtype))
# "(3,)" represents the vector's one-dimensional length
print("V's Shape = {}".format(v.shape))
# Each element can be accessed using "[]" notation
x = v[0]
print("V[0] = {}".format(x))
# Slices can be accessed using ":" notation
y = v[1:]
print("V[1] to V[2] = {}".format(y))


V's Type = int64
V's Shape = (3,)
V[0] = 1
V[1] to V[2] = [2 3]


In [50]:
# Matricies are multiple values collected in a grid
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("M's Type = {}".format(m.dtype))
# "(3, 3)" indicates it has two dimensions, each length 3
print("M's Shape = {}".format(m.shape))
# Each element can be accessed using "[]" notation
x = m[1][2]
print("M[1][2] = {}".format(x))


M's Type = int64
M's Shape = (3, 3)
M[1][2] = 6


In [33]:
# Tensors are any n-dimensional collection of values
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print("T's Type = {}".format(t.dtype))
# "(3, 3, 2, 1)" indicates it has four dimensions
print("T's Shape = {}".format(t.shape))
# Each element can be accessed using "[]" notation
x = t[2][1][1][0]
print("T[2][1][1][0] = {}".format(x))

T's Type = int64
T's Shape = (3, 3, 2, 1)
T[2][1][1][0] = 16


In [39]:
# Sometimes you'll need to change the shape of your data without actually changing its contents
rv = np.array([1,2,3,4])
# "(4,)" indicates it has one dimension with length 4
print("Row Vector's Shape = {}".format(rv.shape))
# to reshape it from a vector to a matrix use reshape
cv = rv.reshape(1,4)
# "(1, 4)" indicates it has two dimensions
print("Column Vector's Shape = {}".format(cv.shape))
# Alternatively you can use the ":" notation to reshape
s = v[None, :]
print("Slice's Shape = {}".format(x.shape))
x = v[:, None]
print("Slice's Shape = {}".format(x.shape))

Row Vector's Shape = (4,)
Column Vector's Shape = (1, 4)
Slice's Shape = (1, 4)
Slice's Shape = (4, 1)


In [53]:
# Element-wise Operations
# Naieve Method of adding 5 to all elements of an array
arr = [1,2,3,4,5]
for i in range(len(values)):
    arr[i] += 5
print("Array = {}".format(arr))
# We can use numpy to do the same thing, but using tensors instead
vect = np.array([1,2,3,4,5])
vect += 5
print("Vector = {}".format(vect))
# We can use this to our advatage if we want to reuse a tensor
print(m)
x = m * 0
print(x)
# We can also perform math on tensors, like exponentiation
y = m * m
print(y)
# Be careful of the shapes; this fails to process:
z = m * t

Array = [6, 7, 8, 9, 10]
Vector = [ 6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,3,2,1) 

In [55]:
# Element-wise Multiplication
m = np.array([[1,2,3],[4,5,6]])
print("M = {}".format(m))
# We could multiply the matrix by a scalar
n = m * 0.25
print("N = {}".format(n))
# We could multiply two matricies
print("M * N = {}".format(m * n))


M = [[1 2 3]
 [4 5 6]]
N = [[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]
M * N = [[0.25 1.   2.25]
 [4.   6.25 9.  ]]


In [58]:
# Matrix Product
a = np.array([[1,2,3,4],[5,6,7,8]])
print("A's Shape = {}".format(a.shape))
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("B's Shape = {}".format(b.shape))
# matrix mulitply a and b
c = np.matmul(a, b)
print("C's Shape = {}".format(c.shape))
# Be careful of the shapes of your matricies; this wont run
np.matmul(b, a)


A's Shape = (2, 4)
B's Shape = (4, 3)
C's Shape = (2, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [59]:
# Dot Product
a = np.array([[1,2],[3,4]])
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [66]:
# Transpose
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
# Consider the transpose just as a different view of your matrix
m_t = m.T
print(m_t)
# Be careful how you modify objects; this modifies both m_t and m
m_t[3][1] = 200
print(m_t)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]
[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


In [73]:
# Neural Network Example
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
print("Inputs = {}".format(inputs))
print("Input's Shape = {}".format(inputs.shape))
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print("Weights = {}".format(weights))
print("Weight's Shape = {}".format(weights.shape))
# Trying this will get a ValueError due to 1x4 and 3x4 not being compatible
#np.matmul(inputs, weights)
# You might think using a Transpose would be a good idea
x = np.matmul(inputs, weights.T)
# Alternatively we could do it the second way:
y = np.matmul(weights, inputs.T)
print(x)
print(y)

Inputs = [[-0.27  0.45  0.64  0.31]]
Input's Shape = (1, 4)
Weights = [[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]
Weight's Shape = (3, 4)
[[-0.01299  0.00664  0.13494]]
[[-0.01299]
 [ 0.00664]
 [ 0.13494]]


In [110]:
def prepare_inputs(inputs):
    # Creates a 2-dimensional ndarray from the given 1-dimensional list
    input_array = np.array([inputs])
    
    # Finds the minimum value in input_array
    min_val = input_array.min()
    # Subtracts min_val from all the elements of input_array
    inputs_minus_min = input_array - min_val

    # Finds the maximum value in inputs_minus_min
    max_val = inputs_minus_min.max()
    # Divides all of the values in inputs_minus_min by max_val
    inputs_div_max = inputs_minus_min / max_val

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

In [146]:
def multiply_inputs(m1, m2):
    # Check the shapes can be used for matrix multiplication
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False

    # Calculates the matrix product of m1 and m2
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)

In [147]:
def find_mean(values):
    # Returns the average of the values in the given Python list
    return np.mean(values)

In [148]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [-1  2  7]
Input minus min: [0 3 8]
Input  Array: [0.    0.375 1.   ]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
